
server:
  port: 8080

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: pass
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    driver-class-name: org.postgresql.Driver
    flyway:
      url: jdbc:postgresql://127.0.0.1:5432
      schemas: postgres
      user: root
      password: pass
      locations: classpath:db/migration

mybatis:
  type-aliases-package: gibson.exam.dowjones.pojo   #   model files